spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.oauth2.authorized-redirect-uri=${OAUTH2_REDIRECT_URI}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-milliseconds=${JWT_EXPIRATION_MILLISECONDS}

app.default-admin.name=${DEFAULT_ADMIN_NAME}
app.default-admin.username=${DEFAULT_ADMIN_USERNAME}
app.default-admin.email=${DEFAULT_ADMIN_EMAIL}
app.default-admin.password=${DEFAULT_ADMIN_PASSWORD}
